---
services:
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    restart: unless-stopped
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      TZ: America/New_York
    volumes:
    - ./my.cnf:/etc/my.cnf:ro
